version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .db.env
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - '7000:7000'
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - db


volumes:
  db:
    driver: local